import random
from game_data import data
from art import logo, vs

def format_data(account):
    account_name = account["name"]
    account_des = account["description"]
    account_country = account["country"]

    return(f"{account_name}, a {account_des}, from {account_country}")

def check_answer(user_guess, a_followers, b_followers):
    """take a user guess and the follower counts and returns if they got it right"""
    # if a_followers > b_followers and user_guess == "a":
    #     print()

    # another way .

    # if a_followers > b_followers:
    #     if user_guess == "a":
    #         return True
    #     else:
    #         return False

    # small way of this ..........
    if a_followers > b_followers:
        return user_guess == "a"   #here it will check ---if user guess = a then a ==a so return true , but if user choice = b, then b == a return false
    else:
        return user_guess == "b"    #same logic as before 


print(logo)

score = 0
game = True
account_b = random.choice(data)

while game:

    account_a = account_b
    account_b = random.choice(data)

    # if somehow account_a and account_b has same data generated by randomly , so we should fix this..

    if account_a == account_b:
        account_b = random.choice(data)

    print(f"Compare A : {format_data(account_a)}")
    print(vs)
    print(f"Against B : {format_data(account_b)}")

    guess = input("Who has more followers ? Type 'A' or 'B' : ").lower()
    
    print("\n" * 20)
    print(logo)
    follower_A = account_a["follower_count"]
    follower_B = account_b["follower_count"]

    is_correct = check_answer(guess, follower_A, follower_B)

    if is_correct:
        score += 1
        print(f"you are right!, current Score = {score}")
    else:
        print(f"You are wrong!, Final score = {score}")
        game = False


